### ISSUE TITLE
callback not defined (isSubscribing, isFollowing)

### ISSUE THREAD

**Issue by JouanMarcel** [Skhmt/tapic.js#1]
Calling the function isSubscribing (or isFollowing) results in "tapic.js:374 Uncaught TypeError: callback is not a function" as callback is not defined.

Not using node.js; Chrome v51

**Comment by Skhmt** [comment]
Fixed the error in a newer version of TAPIC that will be uploaded likely within 24 hrs.

The error message you received is correct, but not useful. isSubscribing and isFollowing are asynchronous functions, so they need a callback function. 

Example:

``` javascript
var folUser = 'skhmt';
var folTarget = 'letsmakefriends';
TAPIC.isFollowing( folUser, folTarget, function( res ) {
  if ( res.isFollowing ) console.log( folUser + ' has been following ' + folTarget + ' since: ' + res.dateFollowed );
  else console.log( folUser + ' is not following ' + folTarget + '.' );
} );
```
