### ISSUE TITLE
Will this keep working after Twitch switches to Helix at the end of 2018?

### ISSUE THREAD

**Issue by ManThatCodesHeroically** [Skhmt/tapic.js#10]
Will this keep working? Will it be updated before then, if updating is required?

**Comment by Skhmt** [comment]
I'll be updating it eventually.

**Comment by ManThatCodesHeroically** [comment]
Great, thanks.

**Comment by Skhmt** [comment]
Sorry to make a liar of myself, but I won't be updating tapic as it would require a full rewrite.

Really sorry.
