### ISSUE TITLE
Error on clear chat

### ISSUE THREAD

**Issue by CreativeCodeCat** [Skhmt/tapic.js#2]
Clear Chat gives this error
`Uncaught TypeError: Cannot read property 'slice' of undefined
    at _msgBan (tapic.js:531)
    at _parseMessage (tapic.js:386)
    at WebSocket.wsMessage (tapic.js:743)`

**Comment by Skhmt** [comment]
Twitch added a roomid to their clearchat messages, which caused tapic to think that a clearchat was a ban/timeout. Released 3.3.6 to fix this issue.
