### ISSUE TITLE
Changes to Twitch

### ISSUE THREAD

**Issue by zSoulweaver** [Skhmt/tapic.js#4]
Don't know if you've seen this already but it looks like Twitch is changing a few things for the new subscription beta [https://discuss.dev.twitch.tv/t/subscriptions-beta-changes/10023](https://discuss.dev.twitch.tv/t/subscriptions-beta-changes/10023)

Just thought I'd let you know.

**Comment by Skhmt** [comment]
Appreciate it. Made changes and updated. I'm not a partner so I can't really test, but it seems like a simple-enough change. Surprisingly I already made most of the move over to `USERNOTICE` in previous versions, but I did have to consolidate everything and remove `twitchnotify` parsing.
