### ISSUE TITLE
Uncaught TypeError: Cannot read property 'user_name' of undefined

### ISSUE THREAD

**Issue by ArmandAbrahamian** [Skhmt/tapic.js#7]
Hi I'm getting an error when doing the setup for Tapic in the example after putting in the Oauth key: 

Uncaught TypeError: Cannot read property 'user_name' of undefined
    at tapic.js:108
    at tapic.js:309

**Comment by Skhmt** [comment]
Anything else to help me track down the bug?

**Comment by ArmandAbrahamian** [comment]
It appears to me that it was a problem on my end. I thought I was using an Oauth key from my Twitch Extension but it was actually a an authentication JWT (JSON Web Token). I'm assuming the error was caused by this being passed in.

**Comment by Skhmt** [comment]
Sounds good!
