### ISSUE TITLE
TAPIC.emit Invalid Parameters

### ISSUE THREAD

**Issue by Chifilly** [Skhmt/tapic.js#8]
If I try and use `TAPIC.emit`, I get;

> Invalid parameters. Usage: TAPIC.emit(eventName, eventDetail);

 except if I use the _follow_ and _host_ events. I tested _follow_, _sub_, _bits_ and _host_. I'm assuming it wants a `JSON.stringify` entry for _eventDetails_ since it fails if I use an object, but it makes things inconsistent because if you fire the event manually, it only works if you send a string, and then the event itself returns a string instead of an object, but if the event is fired normally, it returns an object (at least I assume it returns an object, I don't have a way of testing it, and in the example, it indexes into an object and there's no `JSON.parse`).

The reason this is an issue for me is when the event fires, I want to store a `JSON.stringify` version in a file, but if you `JSON.stringify` a string, it comes out all weird with a lot of escaped characters, and it needs parsing twice

**Comment by Skhmt** [comment]
You mean TAPIC.emit ?

Can you paste in some code that doesn't work as intended and explain what exactly you're trying to do with it?

I made TAPIC.emit() to be complete in the API, but I didn't think anyone else would use it to be honest, although I do use it internally for all the events.

**Comment by Skhmt** [comment]
Although eventDetail really shouldn't have a string type check.

**Comment by Chifilly** [comment]
This is an example I am sending to TAPIC.emit (yes I did mean emit, dunno why I put event)
```javascript
TAPIC.emit('sub', {
    name       : 'chifilly',
    user_id    : 25634037,
    user_type  : 'streamer',
    room_id    : 25634037,
    months     : 24,
    resub      : true,
    plan       : 'Prime',
    planName   : 'Twitch Prime',
    sysMsg     : 'chifilly\shas\ssubscribed\sfor\s6\smonths!',
    joinedText : 'best stream ever!'
});
```

This returns the error 

> Invalid parameters. Usage: TAPIC.emit(eventName, eventDetail);

But if I `JSON.stringify` the object, it works fine, but it causes the side-effect explained in my first post. And the reason I'm using TAPIC.emit is because it's really useful for testing callbacks.

**Comment by Skhmt** [comment]
I know what's wrong but can't fix it for a day or so, sorry. It's just the type checking as I thought.

**Comment by Chifilly** [comment]
No worries, thanks for the super fast response though :)

**Comment by Skhmt** [comment]
should be fixed

**Comment by Chifilly** [comment]
Is the NPM package updated, or do I need to include the git repo manually?

**Comment by Skhmt** [comment]
Oh I knew I forgot something. Npm isn't updated but GitHub is.

**Comment by Skhmt** [comment]
NPM updated, let me know if it works

**Comment by Chifilly** [comment]
Just got around to testing it, and it works perfectly now, thanks very much :)
